name: Python CI test

on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v5
      
      - name: Set up python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest 
      